In [1]:
import pandas as pd
import numpy as np
import os
import openpyxl
from os import listdir
from os.path import isfile, join

In [2]:
   
path=r'C:\Users\etudiant\Downloads\preprocessed data\Feature_base_MvsF'


for i in range(len(listdir(path))):
    s=listdir(path)
    loc=(join(path,s[i]))
    d=listdir(loc)
    print(d)
    for k in range(0,5):
        print(len(listdir(loc)))
        print("value of ",d[1])
        loc1=join(path +'/'+ s[i],d[k])
        data=pd.read_excel(loc1)

        file=d[k].split('.')
        print(loc)

        print(s[i],d[k])
        file = pd.read_excel(loc1)
        print(file)

['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\A2-A1
A2-A1 ALPHA.xlsx
         Mean  Standard Deviation  Variance   Kurtosis      Skew  Activity  \
0   -0.000850            1.098123  1.205874   3.524452  0.002065 -0.000850   
1    0.000273            1.125339  1.266388   3.334993  0.008415  0.000273   
2   -0.001003            1.092574  1.193717   3.373068 -0.000058 -0.001003   
3   -0.001134            1.628707  2.652687  15.161025 -0.337967 -0.001134   
4    0.003419            1.444392  2.086267   4.591901 -0.051506  0.003419   
..        ...                 ...       ...        ...       ...       ...   
103 -0.017580            1.811478  3.281454   3.452114  0.001419 -0.017580   
104 -0.004019            1.803324  3.251979   3.366350  0.053611 -0.004019   
105 -0.002868            2.944443  8.669742   5.445227  0.009836 -0.002868   
106 -0.001550            2.551

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\C3
C3 DELTA.xlsx
         Mean  Standard Deviation     Variance  Kurtosis      Skew  Activity  \
0    0.047382           45.980083  2114.168063  3.678510  0.004860  0.047382   
1    0.003508           44.149502  1949.178517  3.160598 -0.086130  0.003508   
2    0.607062           43.394061  1883.044525  3.101667 -0.042952  0.607062   
3   -0.049852           41.712917  1739.967469  4.001198  0.020622 -0.049852   
4    0.071894           36.463479  1329.585306  3.313250  0.052195  0.071894   
..        ...                 ...          ...       ...       ...       ...   
103  0.135169           36.540057  1335.175758  3.211293  0.040581  0.135169   
104  0.236737           35.260302  1243.288879  3.287436 -0.052058  0.236737   
105  0.227192           35.298176  1245.961239  3.058558  0.006656  0.227192   
106 -0.023725           35.719624  1275.891563  2.984072 -0.022313 -0.023725   
107  0.258594           34.5

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\C4
C4 GAMMA.xlsx
         Mean  Standard Deviation  Variance      Kurtosis        Skew  \
0    0.000013            0.003783  0.000014     80.253912   -1.322760   
1    0.000001            0.003655  0.000013      4.800737    0.016393   
2    0.000670            0.063908  0.004084   5592.723280   64.667498   
3    0.000016            0.011050  0.000122     44.777233    0.804360   
4   -0.000004            0.009941  0.000099      7.987159   -0.027281   
..        ...                 ...       ...           ...         ...   
103  0.000004            0.010309  0.000106      3.321704   -0.008020   
104  0.000005            0.014359  0.000206   1180.747472    0.535945   
105 -0.000005            0.006801  0.000046   3946.600213  -25.521674   
106 -0.000006            0.002939  0.000009      3.538660   -0.000355   
107 -0.000122            0.013074  0.000171  11381.592680 -100.185531   

     Activity  Mobility    Comp

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\F3
F3 ALPHA.xlsx
         Mean  Standard Deviation   Variance  Kurtosis      Skew  Activity  \
0   -0.002534            4.178398  17.459009  2.917356  0.000788 -0.002534   
1    0.004725            4.121362  16.985621  2.988203  0.001168  0.004725   
2   -0.001403            4.023914  16.191884  3.366489  0.008687 -0.001403   
3    0.011278            3.870816  14.983218  8.392819 -0.068730  0.011278   
4    0.021309            3.516680  12.367041  2.871716  0.015942  0.021309   
..        ...                 ...        ...       ...       ...       ...   
103  0.010417            2.901403   8.418142  3.739267 -0.059384  0.010417   
104  0.014809            2.718818   7.391970  3.119078  0.003226  0.014809   
105 -0.000599            2.803450   7.859334  4.180173 -0.017549 -0.000599   
106 -0.000529            2.545103   6.477550  3.272336 -0.003938 -0.000529   
107  0.001716            2.661294   7.082487  3.34

         Mean  Standard Deviation  Variance    Kurtosis      Skew  Activity  \
0    0.000032            0.228880  0.052386    2.970232 -0.024157  0.000032   
1   -0.000047            0.236331  0.055852    3.950718 -0.030443 -0.000047   
2    0.000940            0.250902  0.062952  290.402554  6.855061  0.000940   
3   -0.000055            0.377617  0.142595    4.799693  0.002179 -0.000055   
4   -0.000027            0.357441  0.127764    6.391242  0.007012 -0.000027   
..        ...                 ...       ...         ...       ...       ...   
103 -0.000035            0.316936  0.100448    3.642241 -0.014473 -0.000035   
104 -0.000069            0.321425  0.103314    3.495543 -0.001999 -0.000069   
105  0.000089            0.211002  0.044522   10.570749 -0.200604  0.000089   
106 -0.000009            0.184998  0.034224    3.613145  0.022852 -0.000009   
107  0.000516            0.209432  0.043862   12.768397  0.273818  0.000516   

        Mobility  Complexity  Target  
0     599.96

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\F7
F7 DELTA.xlsx
         Mean  Standard Deviation     Variance  Kurtosis      Skew  Activity  \
0    0.030657           53.949564  2910.555467  3.083510 -0.135959  0.030657   
1   -0.087914           50.945794  2595.473972  3.037265 -0.054282 -0.087914   
2    0.358522           46.717648  2182.538613  4.359172  0.006027  0.358522   
3   -0.046410           26.233309   688.186505  3.444726 -0.000189 -0.046410   
4    0.101632           24.659469   608.089418  3.239050  0.138435  0.101632   
..        ...                 ...          ...       ...       ...       ...   
103 -0.118837           21.463339   460.674935  5.073454 -0.136711 -0.118837   
104  0.242141           19.623827   385.094597  3.741007 -0.231255  0.242141   
105  0.192731           38.420927  1476.167604  3.524023  0.053485  0.192731   
106 -0.072197           39.535082  1563.022740  2.981203  0.099791 -0.072197   
107 -0.006036           38.2

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\F8
F8 GAMMA.xlsx
             Mean  Standard Deviation  Variance     Kurtosis       Skew  \
0    9.120839e-07            0.004390  0.000019    14.075398   0.353849   
1    1.534106e-06            0.004894  0.000024     4.357144   0.003201   
2    1.914292e-04            0.021579  0.000466  6102.239545  58.457650   
3   -4.483158e-07            0.009783  0.000096    54.438478   0.801552   
4   -9.723759e-06            0.008721  0.000076    17.646028  -0.037177   
..            ...                 ...       ...          ...        ...   
103  1.710728e-06            0.008951  0.000080     3.318741  -0.012419   
104 -3.300899e-05            0.017081  0.000292  3055.932257 -24.415021   
105 -3.020118e-06            0.004379  0.000019  1091.467650 -10.072460   
106  6.370683e-06            0.003128  0.000010    16.251465   0.000345   
107  2.169642e-04            0.021889  0.000479  5479.394689  58.935929   

       

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\Fp1
Fp1 THETA.xlsx
         Mean  Standard Deviation    Variance  Kurtosis      Skew  Activity  \
0   -0.141253           12.461938  155.299888  3.318086 -0.009898 -0.141253   
1   -0.107620           12.754152  162.668387  2.991226 -0.042695 -0.107620   
2   -0.047949           13.005270  169.137041  3.081909  0.053938 -0.047949   
3   -0.013015           10.607050  112.509501  3.130670  0.080775 -0.013015   
4   -0.047726           10.906463  118.950930  3.500254  0.033148 -0.047726   
..        ...                 ...         ...       ...       ...       ...   
103  0.111817            7.557052   57.109035  3.245926 -0.115621  0.111817   
104 -0.108053            7.030858   49.432963  3.402814 -0.016416 -0.108053   
105  0.168787            8.828635   77.944788  4.161017  0.010362  0.168787   
106  0.076635            8.216167   67.505393  3.104505 -0.043651  0.076635   
107  0.136634            8.474896   7

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\Fz
Fz ALPHA.xlsx
         Mean  Standard Deviation   Variance  Kurtosis      Skew  Activity  \
0   -0.003300            3.988532  15.908387  2.894080  0.005009 -0.003300   
1    0.003098            4.065868  16.531284  3.198180 -0.007517  0.003098   
2   -0.001787            3.892847  15.154255  3.739253  0.009118 -0.001787   
3    0.013815            3.836490  14.718654  3.626910  0.012730  0.013815   
4    0.016842            3.680428  13.545553  2.863989 -0.014044  0.016842   
..        ...                 ...        ...       ...       ...       ...   
103  0.005246            3.161456   9.994807  3.029979 -0.018563  0.005246   
104  0.013127            3.186599  10.154411  3.190856 -0.007551  0.013127   
105 -0.000260            2.849095   8.117344  3.767480 -0.005949 -0.000260   
106 -0.001645            2.621811   6.873895  3.308711 -0.008645 -0.001645   
107 -0.000683            2.652113   7.033702  3.28

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\O1
O1 BETA.xlsx
         Mean  Standard Deviation  Variance   Kurtosis      Skew  Activity  \
0    0.000069            0.228454  0.052191   3.392963 -0.078823  0.000069   
1    0.000004            0.238224  0.056750   5.490292 -0.147932  0.000004   
2    0.000566            0.218639  0.047803  71.662542  2.326691  0.000566   
3    0.000005            0.530397  0.281321   7.629834  0.034240  0.000005   
4   -0.000033            0.508126  0.258192   9.279189  0.013961 -0.000033   
..        ...                 ...       ...        ...       ...       ...   
103  0.000041            0.337630  0.113994   3.096177  0.021156  0.000041   
104  0.000042            0.387916  0.150479   3.448296  0.037079  0.000042   
105  0.000072            0.194513  0.037835  12.211639 -0.112700  0.000072   
106 -0.000022            0.169555  0.028749   4.686561 -0.029731 -0.000022   
107 -0.001069            0.212685  0.045235  63.703

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\O2
O2 DELTA.xlsx
         Mean  Standard Deviation     Variance  Kurtosis      Skew  Activity  \
0    0.305525           66.807947  4463.301744  4.010809  0.171182  0.305525   
1   -0.085494           65.261216  4259.026369  3.741368  0.277438 -0.085494   
2    0.306589           62.913047  3958.051444  3.357755  0.016618  0.306589   
3   -0.073912           44.873987  2013.674673  3.354594  0.072907 -0.073912   
4    0.061481           42.949412  1844.651972  3.437132  0.113666  0.061481   
..        ...                 ...          ...       ...       ...       ...   
103  0.149854           38.883745  1511.945626  3.190693  0.173797  0.149854   
104  0.175233           38.091650  1450.973790  3.553395  0.042923  0.175233   
105  0.223855           47.273675  2234.800374  3.304264  0.160325  0.223855   
106 -0.072814           44.774192  2004.728299  3.143879  0.124759 -0.072814   
107  0.422059           46.2

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\P3
P3 GAMMA.xlsx
             Mean  Standard Deviation  Variance     Kurtosis       Skew  \
0   -9.486225e-06            0.005015  0.000025  2036.609783 -15.461647   
1    2.154863e-06            0.003603  0.000013     5.645993   0.010403   
2    2.287658e-04            0.022295  0.000497  8534.434592  84.686797   
3    8.130333e-07            0.013371  0.000179    12.209174  -0.002646   
4   -8.221813e-06            0.011612  0.000135     5.978984  -0.022205   
..            ...                 ...       ...          ...        ...   
103 -6.321242e-06            0.007827  0.000061     3.149719  -0.002881   
104 -3.034287e-05            0.033824  0.001144  4146.548387 -11.980778   
105  1.709885e-06            0.006231  0.000039  3866.220743 -25.589773   
106  4.177593e-07            0.002745  0.000008     4.264353  -0.002751   
107  4.267319e-04            0.043044  0.001853  5547.974553  59.659766   

       

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\P4
P4 THETA.xlsx
         Mean  Standard Deviation    Variance  Kurtosis      Skew  Activity  \
0   -0.211112           18.619122  346.671705  3.772346  0.084216 -0.211112   
1    0.104643           18.085990  327.103046  3.230776  0.017108  0.104643   
2    0.040722           18.596891  345.844339  3.537325  0.049888  0.040722   
3    0.109777           15.704443  246.629525  2.985578  0.028074  0.109777   
4   -0.126069           15.571099  242.459118  2.988844 -0.024319 -0.126069   
..        ...                 ...         ...       ...       ...       ...   
103 -0.072349           12.712607  161.610387  3.269692  0.094911 -0.072349   
104 -0.145356           12.469977  155.500323  3.922671  0.063881 -0.145356   
105 -0.012309           13.347145  178.146277  3.177638  0.133347 -0.012309   
106  0.254001           13.291706  176.669443  3.308581  0.131411  0.254001   
107  0.263726           14.657621  214.

C:\Users\etudiant\Downloads\Arithmetic preprocessed data\Feature_base_MvsF\T3
T3 ALPHA.xlsx
         Mean  Standard Deviation   Variance   Kurtosis      Skew  Activity  \
0   -0.000876            4.483441  20.101247   3.189328  0.031698 -0.000876   
1   -0.003489            4.461342  19.903576   3.407736  0.015554 -0.003489   
2    0.001816            4.122539  16.995327   3.122730  0.010457  0.001816   
3    0.026625            6.181092  38.205894  68.966556 -0.910874  0.026625   
4    0.023320            4.392031  19.289933   2.945397  0.041344  0.023320   
..        ...                 ...        ...        ...       ...       ...   
103  0.003862            3.426655  11.741963   2.956322  0.011112  0.003862   
104 -0.011275            3.220049  10.368714   3.388458 -0.000175 -0.011275   
105  0.002044            2.640178   6.970539   4.583740  0.007583  0.002044   
106 -0.000356            2.302013   5.299264   4.186450  0.021990 -0.000356   
107 -0.000680            2.389537   5.7

         Mean  Standard Deviation     Variance  Kurtosis      Skew  Activity  \
0    0.122215           41.261284  1702.493521  3.977214  0.165248  0.122215   
1    0.104351           40.320496  1625.742404  3.276432  0.083868  0.104351   
2    0.639392           40.912123  1673.801831  3.203260  0.163000  0.639392   
3   -0.122253           37.972837  1441.936368  3.224025  0.095551 -0.122253   
4   -0.066187           40.200767  1616.101631  3.421938  0.132947 -0.066187   
..        ...                 ...          ...       ...       ...       ...   
103 -0.126262           35.645990  1270.636628  5.900628 -0.450006 -0.126262   
104 -0.742546           31.089786   966.574793  3.664541 -0.189146 -0.742546   
105  0.222236           32.402988  1049.953623  6.411019 -0.526992  0.222236   
106 -0.038867           29.276522   857.114753  3.214179 -0.055547 -0.038867   
107 -1.103363           30.293160   917.675569  2.788557 -0.033736 -1.103363   

     Mobility    Complexity  Target  
0

T5 GAMMA.xlsx
             Mean  Standard Deviation  Variance      Kurtosis        Skew  \
0    1.190783e-06            0.003811  0.000015    346.125886   -3.935226   
1   -1.466175e-06            0.003793  0.000014     12.398614    0.029617   
2    3.066492e-04            0.029947  0.000897  11229.179626  100.373772   
3   -4.083044e-06            0.014689  0.000216     73.737520   -0.055609   
4    4.080246e-08            0.011377  0.000129      4.449459   -0.026541   
..            ...                 ...       ...           ...         ...   
103 -1.267802e-06            0.008314  0.000069      3.353316   -0.002083   
104 -6.782533e-05            0.013453  0.000181   2502.145635  -27.125999   
105  2.398459e-06            0.004390  0.000019   1090.743004   -9.947212   
106  3.701628e-06            0.002797  0.000008      5.658402    0.006339   
107 -4.593667e-05            0.007433  0.000055   9427.235705  -85.961047   

         Activity  Mobility  Complexity  Target  
0    1.1907

In [3]:


from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import confusion_matrix



path=r'C:\Users\etudiant\Downloads\preprocessed data\Feature_perf_MvsF'


for i in range(len(listdir(path))):#getting all the list of channel folder 
    s=listdir(path)
    loc=(join(path,s[i]))
    d=listdir(loc)
    print(d)
    for k in range(0,5):        #accessing al the feature file file of each band for every channel
        print(len(listdir(loc)))
        print("value of ",d[1])
        loc1=join(path +'/'+ s[i],d[k])
        data=pd.read_excel(loc1)

        bnd=d[k].split('.')

        print(s[i],d[k])
        file = pd.read_excel(loc1)
    #print(file.columns.values)
        col= [x for x in file.columns if x != 'Target']
        X = file.drop(columns=['Target'])
        y = file.drop(columns=col)
    
        X_train, X_test, y_train, y_test = train_test_split(X, y) #spliiting the data into test and training
        print(X_train.shape)
        print(y_train.shape)
#Import svm model

#Create a svm Classifier
        clf = svm.SVC(kernel='poly') # Linear Kernel

#Train the model using the training sets
        clf.fit(X_train, y_train)

#Predict the response for test dataset
        y_pred = clf.predict(X_test)
    
    


    #accuracy=metrics.accuracy_score(y_test, y_pred)
    #sensitivity=metrics.recall_score(y_test, y_pred)
   
        cm1 = confusion_matrix(y_test,y_pred)
        print('Confusion Matrix : \n', cm1)

        total1=sum(sum(cm1))
#####from confusion matrix calculate accuracy
        accuracy1=(cm1[0,0]+cm1[1,1])/total1
        print ('Accuracy : ', accuracy1)

        sensitivity1 = cm1[0,0]/(cm1[0,0]+cm1[0,1])
        print('Sensitivity : ', sensitivity1 )

        specificity1 = cm1[1,1]/(cm1[1,0]+cm1[1,1])
        print('Specificity : ', specificity1)
    
    
    
        w=openpyxl.load_workbook(r"C:\Users\etudiant\Downloads\preprocessed data\svm_Feature_Perf_MvsF.xlsx")
    #writing all the outputs to the excel file 
        sheet=w.get_sheet_by_name('Feuil1')
        r=sheet.max_row
        sheet.cell(row = 1, column = 1).value="Channel"
        sheet.cell(row = 1, column = 2).value="Band"
        sheet.cell(row = 1, column = 3).value="Accuracy"
        sheet.cell(row = 1, column = 4).value="Sensitivity"
        sheet.cell(row = 1, column = 5).value="Specivity"
    
        sheet.cell(row=(r+1),column=1).value=s[i]
        sheet.cell(row=(r+1),column=2).value=bnd[0]
    
        sheet.cell(row = (r+1), column = 3).value=accuracy1
        sheet.cell(row = (r+1), column = 4).value=sensitivity1
        sheet.cell(row = (r+1), column = 5).value=specificity1

        w.save(r"C:\Users\etudiant\Downloads\preprocessed data\svm_Feature_Perf_MvsF.xlsx")
   
       

['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
A2-A1 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 24]
 [ 0 17]]
Accuracy :  0.4146341463414634
Sensitivity :  0.0
Specificity :  1.0
5
value of  

C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BETA.xlsx
A2-A1 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [22  2]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.08333333333333333
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


A2-A1 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 3 20]
 [ 0 18]]
Accuracy :  0.5121951219512195
Sensitivity :  0.13043478260869565
Specificity :  1.0
5
value of  BETA.xlsx
A2-A1 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 22]
 [ 0 18]]
Accuracy :  0.4634146341463415
Sensitivity :  0.043478260869565216
Specificity :  1.0
5
value of  BETA.xlsx
A2-A1 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


 [[20  0]
 [20  1]]
Accuracy :  0.5121951219512195
Sensitivity :  1.0
Specificity :  0.047619047619047616
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
C3 ALPHA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 27]
 [ 0 13]]
Accuracy :  0.34146341463414637
Sensitivity :  0.03571428571428571
Specificity :  1.0
5
value of  BETA.xlsx
C3 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 19]
 [ 0 21]]
Accuracy :  0.5365853658536586
Sensitivity :  0.05
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


5
value of  BETA.xlsx
C3 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [24  0]]
Accuracy :  0.4146341463414634
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


C3 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
C3

C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[21  0]
 [16  4]]
Accuracy :  0.6097560975609756
Sensitivity :  1.0
Specificity :  0.2
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
C4 ALPHA.xlsx
(121, 8)
(121, 1)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix : 
 [[ 0 22]
 [ 0 19]]
Accuracy :  0.4634146341463415
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
C4 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 19]
 [ 0 21]]
Accuracy :  0.5365853658536586
Sensitivity :  0.05
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
C4 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 25]
 [ 0 16]]
Accuracy :  0.3902439024390244
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
C4 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [21  1]]
Accuracy :  0.4878048780487805
Sensitivity :  1.0
Specificity :  0.045454545454545456
5
value of  BETA.xlsx
C4 THETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 25]
 [ 0 16]]
Accuracy :  0.3902439024390244
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
Cz ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
Cz BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 3 23]
 [ 0 15]]
Accuracy :  0.43902439024390244
Sensitivity :  0.11538461538461539
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Cz DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 23]
 [ 0 18]]
Accuracy :  0.43902439024390244
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
Cz GAMMA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 24]
 [ 0 17]]
Accuracy :  0.4146341463414634
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
Cz THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
F3 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 16]
 [ 0 24]]
Accuracy :  0.6097560975609756
Sensitivity :  0.058823529411764705
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


F3 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [24  0]]
Accuracy :  0.4146341463414634
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
F3 DELTA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[20  1]
 [20  0]]
Accuracy :  0.4878048780487805
Sensitivity :  0.9523809523809523
Specificity :  0.0
5
value of  BETA.xlsx
F3 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


5
value of  BETA.xlsx
F3 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [21  2]]
Accuracy :  0.4878048780487805
Sensitivity :  1.0
Specificity :  0.08695652173913043
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


F4 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [24  0]]
Accuracy :  0.4146341463414634
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
F4 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [24  0]]
Accuracy :  0.4146341463414634
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
F4 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [24  0]]
Accuracy :  0.4146341463414634
Sensitivity :  1.0
Specificity :  0.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


5
value of  BETA.xlsx
F4 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


F4 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 24]
 [ 0 17]]
Accuracy :  0.4146341463414634
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
F7 ALPHA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[21  0]
 [20  0]]
Accuracy :  0.5121951219512195
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
F7 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[20  0]
 [20  1]]
Accuracy :  0.5121951219512195
Sensitivity :  1.0
Specificity :  0.047619047619047616
5
value of  BETA.xlsx
F7 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 

C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 0 26]
 [ 0 15]]
Accuracy :  0.36585365853658536
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
F7 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 6 15]
 [ 0 20]]
Accuracy :  0.6341463414634146
Sensitivity :  0.2857142857142857
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
F7 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 22]
 [ 0 19]]
Accuracy :  0.4634146341463415
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
F8

C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 21]
 [ 0 20]]
Accuracy :  0.4878048780487805
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
F8 BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  1]
 [20  2]]
Accuracy :  0.4878048780487805
Sensitivity :  0.9473684210526315
Specificity :  0.09090909090909091
5
value of  BETA.xlsx
F8 DELTA.xlsx
(121, 8)
(121, 1)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


Confusion Matrix : 
 [[ 0 20]
 [ 0 21]]
Accuracy :  0.5121951219512195
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
F8 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 20]
 [ 0 20]]
Accuracy :  0.5121951219512195
Sensitivity :  0.047619047619047616
Specificity :  1.0
5
value of  BETA.xlsx
F8 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[14  0]
 [27  0]]
Accuracy :  0.34146341463414637
Sensitivity :  1.0
Specificity :  0.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Fp1 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 28]
 [ 0 13]]
Accuracy :  0.3170731707317073
Sensitivity :  0.0
Specificity :  1.0
5

C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).



value of  BETA.xlsx
Fp1 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 20]
 [ 0 20]]
Accuracy :  0.5121951219512195
Sensitivity :  0.047619047619047616
Specificity :  1.0
5
value of  BETA.xlsx
Fp1 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


Fp1 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 3 16]
 [ 5 17]]
Accuracy :  0.4878048780487805
Sensitivity :  0.15789473684210525
Specificity :  0.7727272727272727
5
value of  BETA.xlsx
Fp1 THETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 22]
 [ 0 19]]
Accuracy :  0.4634146341463415
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
Fp2 ALPHA.xlsx
(121, 8)
(121, 1)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix : 
 [[22  0]
 [18  1]]
Accuracy :  0.5609756097560976
Sensitivity :  1.0
Specificity :  0.05263157894736842
5
value of  BETA.xlsx
Fp2 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
Fp2 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 22]
 [ 0 18]]
Accuracy :  0.4634146341463415
Sensitivity :  0.043478260869565216
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Fp2 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


Fp2 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 19]
 [ 0 22]]
Accuracy :  0.5365853658536586
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
Fz ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[16  2]
 [22  1]]
Accuracy :  0.4146341463414634
Sensitivity :  0.8888888888888888
Specificity :  0.043478260869565216
5
value of  BETA.xlsx
Fz BETA.xlsx
(121, 8)
(121, 1)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix : 
 [[16  0]
 [25  0]]
Accuracy :  0.3902439024390244
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
Fz DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 21]
 [ 0 20]]
Accuracy :  0.4878048780487805
Sensitivity :  0.0
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
Fz GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 22]
 [ 0 19]]
Accuracy :  0.4634146341463415
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Fz THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 2 18]
 [ 0 21]]
Accuracy :  0.5609756097560976
Sensitivity :  0.1
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


O1 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 29]
 [ 0 12]]
Accuracy :  0.2926829268292683
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


O1 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
O1 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 24]
 [ 0 17]]
Accuracy :  0.4146341463414634
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
O1 GAMMA.xlsx
(121, 8)
(121, 1)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix : 
 [[ 3 17]
 [ 2 19]]
Accuracy :  0.5365853658536586
Sensitivity :  0.15
Specificity :  0.9047619047619048
5
value of  BETA.xlsx
O1 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [18  6]]
Accuracy :  0.5609756097560976
Sensitivity :  1.0
Specificity :  0.25


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
O2 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  1]
 [21  2]]
Accuracy :  0.4634146341463415
Sensitivity :  0.9444444444444444
Specificity :  0.08695652173913043
5

C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



value of  BETA.xlsx
O2 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


O2 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 22]
 [ 0 18]]
Accuracy :  0.4634146341463415
Sensitivity :  0.043478260869565216
Specificity :  1.0
5
value of  BETA.xlsx
O2 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
O2 THETA.xlsx
(121, 8)
(121, 1)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
P3 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 2 21]
 [ 0 18]]
Accuracy :  0.4878048780487805
Sensitivity :  0.08695652173913043
Specificity :  1.0
5
value of  BETA.xlsx
P3 BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 25]
 [ 0 16]]
Accuracy :  0.3902439024390244
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


P3 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[21  0]
 [19  1]]
Accuracy :  0.5365853658536586
Sensitivity :  1.0
Specificity :  0.05
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


P3 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
P3 THETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 19]
 [ 0 21]]
Accuracy :  0.5365853658536586
Sensitivity :  0.05
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
P4 ALPHA.xlsx
(121, 8)
(121, 1)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


Confusion Matrix : 
 [[ 1 20]
 [ 0 20]]
Accuracy :  0.5121951219512195
Sensitivity :  0.047619047619047616
Specificity :  1.0
5
value of  BETA.xlsx
P4 BETA.xlsx
(121, 8)

C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



(121, 1)
Confusion Matrix : 
 [[17  0]
 [24  0]]
Accuracy :  0.4146341463414634
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
P4 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[21  0]
 [20  0]]
Accuracy :  0.5121951219512195
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
P4 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 24]
 [ 0 16]]
Accuracy :  0.4146341463414634
Sensitivity :  0.04
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
P4 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 20]
 [ 0 21]]
Accuracy :  0.5121951219512195
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']

C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)



5
value of  BETA.xlsx
Pz ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 23]
 [ 0 18]]
Accuracy :  0.43902439024390244
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


Pz BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[16  0]
 [25  0]]
Accuracy :  0.3902439024390244
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
Pz DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
Pz GAMMA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(121, 8)
(121, 1)
Confusion Matrix : 
 [[17  0]
 [23  1]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.041666666666666664
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


Pz THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[10  0]
 [29  2]]
Accuracy :  0.2926829268292683
Sensitivity :  1.0
Specificity :  0.06451612903225806
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
T3 ALPHA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 22]
 [ 0 19]]
Accuracy :  0.4634146341463415
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
T3 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 21]
 [ 0 20]]
Accuracy :  0.4878048780487805
Sensitivity :  0.0
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
T3 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 22]
 [ 0 19]]
Accuracy :  0.4634146341463415
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


T3 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 24]
 [ 0 17]]
Accuracy :  0.4146341463414634
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


T3 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 24]
 [ 0 17]]
Accuracy :  0.4146341463414634
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
T4 ALPHA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[21  0]
 [20  0]]
Accuracy :  0.5121951219512195
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
T4 BETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 19]
 [ 0 21]]
Accuracy :  0.5365853658536586
Sensitivity :  0.05
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
T4 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [23  0]]
Accuracy :  0.43902439024390244
Sensitivity :  1.0
Specificity :  0.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


5
value of  BETA.xlsx
T4 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  2]
 [18  3]]
Accuracy :  0.5121951219512195
Sensitivity :  0.9
Specificity :  0.14285714285714285
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


T4 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 21]
 [ 0 20]]
Accuracy :  0.4878048780487805
Sensitivity :  0.0
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx
T5 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 22]
 [ 0 18]]
Accuracy :  0.4634146341463415
Sensitivity :  0.043478260869565216
Specificity :  1.0
5
value of  BETA.xlsx
T5 BETA.xlsx
(121, 8)

C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).



(121, 1)
Confusion Matrix : 
 [[ 0 23]
 [ 0 18]]
Accuracy :  0.43902439024390244
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
T5 DELTA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 26]
 [ 0 15]]
Accuracy :  0.36585365853658536
Sensitivity :  0.0
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array

5
value of  BETA.xlsx
T5 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 3 19]
 [ 1 18]]
Accuracy :  0.5121951219512195
Sensitivity :  0.13636363636363635
Specificity :  0.9473684210526315
5
value of  BETA.xlsx
T5 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 23]
 [ 0 17]]
Accuracy :  0.43902439024390244
Sensitivity :  0.041666666666666664
Specificity :  1.0
['ALPHA.xlsx', 'BETA.xlsx', 'DELTA.xlsx', 'GAMMA.xlsx', 'THETA.xlsx']
5
value of  BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


T6 ALPHA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[19  0]
 [22  0]]
Accuracy :  0.4634146341463415
Sensitivity :  1.0
Specificity :  0.0
5
value of  BETA.xlsx
T6 BETA.xlsx


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 0 20]
 [ 0 21]]
Accuracy :  0.5121951219512195
Sensitivity :  0.0
Specificity :  1.0
5
value of  BETA.xlsx
T6 DELTA.xlsx
(121, 8)


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


(121, 1)
Confusion Matrix : 
 [[21  1]
 [19  0]]
Accuracy :  0.5121951219512195
Sensitivity :  0.9545454545454546
Specificity :  0.0
5
value of  BETA.xlsx
T6 GAMMA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[18  0]
 [21  2]]
Accuracy :  0.4878048780487805
Sensitivity :  1.0
Specificity :  0.08695652173913043


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


5
value of  BETA.xlsx
T6 THETA.xlsx
(121, 8)
(121, 1)
Confusion Matrix : 
 [[ 1 18]
 [ 0 22]]
Accuracy :  0.5609756097560976
Sensitivity :  0.05263157894736842
Specificity :  1.0


C:\Users\etudiant\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\etudiant\anaconda3\lib\site-packages\ipykernel_launcher.py:68: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).


In [76]:
import pickle
with open('svm',wb) as f:
    pickle.dump(clf,f)

NameError: name 'wb' is not defined